id: P000564
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:47:11.993341
source_metadata:
  id: bdr:W23201
  title: རི་ཆོས་ལྷན་ཐབས
  author: ''
  volumes:
    63d8fe4b8edd4edd96f21279ec4a70b3:
      image_group_id: I0843
      title: ''
      volume_number: 1
      total_pages: 253
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
